#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Feb 24 15:06:51 2022

@author: wukong
"""

import nltk
nltk.download('punkt')

from nltk.tokenize import word_tokenize
tokenizer = word_tokenize

import torch
from torchtext.legacy import data
from torchtext.legacy import datasets

SEED = 1234

torch.manual_seed(SEED)
torch.backends.cudnn.deterministic = True

TEXT = data.Field(tokenize = tokenizer, include_lengths = True)
LABEL = data.LabelField(dtype = torch.float)


train_data, test_data = datasets.IMDB.splits(TEXT, LABEL)